FROM python:3.11-slim as builder
WORKDIR /app
COPY web/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY web/ /app/web/

FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /app /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
EXPOSE 8080
CMD ["uvicorn", "web.core.main:app", "--host", "0.0.0.0", "--port", "8080"]